--- !ruby/object:NBayes::Base
debug: false
k: 1
binarized: true
log_vocab: false
assume_uniform: true
vocab:
  hi: 1
  hello: 1
  excuse: 1
  me: 1
  hey: 1
  show: 1
  your: 1
  resume: 1
  where: 1
  can: 1
  i: 1
  find: 1
  download: 1
  brian: 1
  s: 1
  cv: 1
  you: 1
  send: 1
  want: 1
  the: 1
  link: 1
  of: 1
  tell: 1
  about: 1
  yourself: 1
  who: 1
  are: 1
  how: 1
  day: 1
  weekend: 1
  I: 1
  have: 1
  a: 1
  question: 1
  contact: 1
  what: 1
  is: 1
  phone: 1
  number: 1
  do: 1
  get: 1
  in: 1
  touch: 1
  with: 1
  reach: 1
data:
  hi_enquiry:
    :tokens:
      hi: 1
      hello: 1
      excuse: 1
      me: 1
      hey: 1
    :total_tokens: 5
    :examples: 4
  show_resume_enquiry:
    :tokens:
      show: 1
      me: 1
      your: 2
      resume: 2
      where: 1
      can: 1
      i: 1
      find: 1
    :total_tokens: 10
    :examples: 2
  download_resume_enquiry:
    :tokens:
      download: 2
      your: 3
      resume: 3
      can: 2
      i: 2
      brian: 1
      s: 1
      cv: 1
      you: 1
      send: 1
      me: 1
      want: 1
      the: 1
      link: 1
      of: 1
    :total_tokens: 22
    :examples: 4
  self_intro_enquiry:
    :tokens:
      tell: 1
      me: 1
      about: 1
      yourself: 1
      who: 1
      are: 1
      you: 1
    :total_tokens: 7
    :examples: 2
  greeting_enquiry:
    :tokens:
      how: 3
      are: 1
      you: 1
      s: 2
      your: 2
      day: 1
      weekend: 1
      I: 1
      have: 1
      a: 1
      question: 1
    :total_tokens: 15
    :examples: 4
  contact_enquiry:
    :tokens:
      can: 3
      i: 3
      have: 1
      your: 2
      contact: 1
      what: 1
      is: 1
      phone: 1
      number: 1
      how: 2
      I: 1
      find: 1
      you: 3
      do: 1
      get: 1
      in: 1
      touch: 1
      with: 1
      where: 1
      reach: 1
    :total_tokens: 28
    :examples: 5
